# Generated by Django 6.0.1 on 2026-01-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterial',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.material'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='products.product'),
        ),
    ]
